### ISSUE TITLE
Missing am_audio_transforms in modules/augmentations.py.

### ISSUE THREAD

**Issue by quqixun** [LIHANG-HONG/birdclef2023-2nd-place-solution#1]
Some am_audio_transforms augmentations, such as AddBackgroundNoise, Gain and GainTransition, cannot be found in modules/augmentations.py.

Could you please provide these functions?

**Comment by LIHANG-HONG** [comment]
Hi, quqixun.
The functions you mentioned are provided by audiomentations library.
You can find them on github.

**Comment by LIHANG-HONG** [comment]
> Some am_audio_transforms augmentations, such as AddBackgroundNoise, Gain and GainTransition, cannot be found in modules/augmentations.py.
> 
> Could you please provide these functions?

Hi, quqixun.
The functions you mentioned are provided by audiomentations library.
You can find them on github.

**Comment by quqixun** [comment]
@LIHANG-HONG Thansk. I should read code more carefully.
